kotlin.code.style=official

# Plugin/Library Versions
# 2.0.20
versionKotlin = 2.0.+
# 1.9.0-RC.2 is latest Kotlin 2.0.0 (2024-08)
versionCoroutines = 1.9.0-RC.2
#
versionKtor = 2.3.+
# 1.7.2
versionKotlinxSerializationJson = 1.7.+

# 2.23.1
versionLog4j = 2.23.+
# 2.0.16
versionSlf4j = 	2.0.+
# 5.1.4
versionKotlinLogging = 5.1.+

# 5.10.3
versionJUnit = 5.10.+
# 1.10.3
versionJUnitPlatformLauncher = 1.10.+

#Warnings
org.gradle.warning.mode=all