kotlin.code.style=official

# Plugin/Library Versions
versionKotlin = 2.0.0
#Kotlinx Coroutines - 2024-08 Latest is 1.9.0-RC (Kotlin 2.0.0), latest main release is 1.8.1
versionCoroutines = 1.9.0-RC
versionKtor = 2.3.12
versionKotlinxSerializationJson = 1.7.1

versionLog4j = 2.23.1
versionSlf4j = 	2.0.13
versionKotlinLogging = 5.1.4

versionGmazzoBuildconfig = 3.0.0

versionTouchportal = 8.3.0

versionJUnit = 5.10.3
versionJUnitPlatformLauncher = 1.10.3

#Warnings
org.gradle.warning.mode=all